# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FgKHPWKAJOCsUjHjRihVgVqBpIBZGVjz
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv("sample_us_accidents.csv")
df['Start_Time'] = pd.to_datetime(df['Start_Time'])
df['Hour'] = df['Start_Time'].dt.hour
df['DayOfWeek'] = df['Start_Time'].dt.day_name()
df = df.dropna(subset=['Weather_Condition', 'Start_Lat', 'Start_Lng'])
hourly_accidents = df['Hour'].value_counts().sort_index()
plt.figure(figsize=(10, 5))
plt.plot(hourly_accidents.index, hourly_accidents.values, marker='o', color='purple')
plt.title('Accidents by Hour of Day')
plt.xlabel('Hour of Day')
plt.ylabel('Number of Accidents')
plt.grid(True)
plt.xticks(range(0, 24))
plt.tight_layout()
plt.show()
day_order = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
weekly_accidents = df['DayOfWeek'].value_counts().reindex(day_order)
plt.figure(figsize=(8, 5))
plt.bar(weekly_accidents.index, weekly_accidents.values, color='orange')
plt.title('Accidents by Day of Week')
plt.xlabel('Day of Week')
plt.ylabel('Number of Accidents')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()
top_weather = df['Weather_Condition'].value_counts().head(10)
plt.figure(figsize=(12, 6))
plt.bar(top_weather.index, top_weather.values, color='skyblue')
plt.title('Top 10 Weather Conditions in Accidents')
plt.xlabel('Weather Condition')
plt.ylabel('Number of Accidents')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()
pivot_table = pd.pivot_table(df, index='DayOfWeek', columns='Hour', values='ID', aggfunc='count')
pivot_table = pivot_table.reindex(index=day_order)
plt.figure(figsize=(12, 6))
plt.imshow(pivot_table, cmap='plasma', aspect='auto')
plt.title('Accident Frequency by Day and Hour')
plt.xlabel('Hour of Day')
plt.ylabel('Day of Week')
plt.colorbar(label='Number of Accidents')
plt.xticks(ticks=range(24), labels=range(24))
plt.yticks(ticks=range(7), labels=day_order)
plt.tight_layout()
plt.show()